<?php


namespace Cubetiq\Litegen\Generators\Controller;


use Cubetiq\Litegen\Base\BaseGeneratorRepository;
use Cubetiq\Litegen\Base\traits\SubProjectContoller;
use Cubetiq\Litegen\Configuration;
use Cubetiq\Litegen\Generators\ControllerGeneratorInterface;

class SimpleControllerGenerator extends BaseGeneratorRepository implements ControllerGeneratorInterface
{
    public function parse()
    {
        $controllers=Configuration::get_controllers_data();
        parent::parse(); // TODO: Change the autogenerated stub
    }

    protected function getContent()
    {

    }

    protected function getTargetPath()
    {
        return Configuration::get_project_path()."/app/Http/Controllers/";
    }
}
